### PR TITLE
allow v-models

### PR DESCRIPTION
**Pull request by ejlocop**

### CODE REVIEW

**Comment by euvl** [comment]
lol

**Comment by ejlocop** [comment]
yeah sorry. i was trying to create pull request.

**Comment by ejlocop** [comment]
hey, i want to help. i want to merge file that supports v-model. I've forgot how. lol

**Comment by euvl** [comment]
Thanks 😸 
You will need to:

1.  create a fork
2. update the files
3. create a pull request from your fork's branch to master 

Cheers 👍

**Pull request closed without merging**
