### PR TITLE
buttonBackground prop to customize the inner btn

### PR DESCRIPTION
**Pull request by cristiandan**

### CODE REVIEW

**Comment by cristiandan** [comment]
can you check this PR @euvl ?

**Comment by euvl** [comment]
Hey sure, sorry i am having a lot of work last couple of weeks. 

I will review it when i have at least a little of free time and not feel sick from javascript 😆

**Comment by cristiandan** [comment]
Oh man, sorry to hear that. No worries 😄

**Comment by euvl** [comment]
Hey, looks good to me 👍 The only request wuld be to rename a prop to `buttonColor` or `switchColor` because we already have one `color` prop for component's background and `buttonBackground` sounds a bit confusing to me (if you think about the whole component rather than particular html element within it) 

Nice work 👍

**Comment by euvl** [comment]
Merged, will publish new version tonight

**Comment by cristiandan** [comment]
thank you @euvl

**Comment by cristiandan** [comment]
let me know pls when you have time for the new version on npm 😄

**Pull request merged**
